---
version: '3'
services:
  arangodb:
    image: arangodb:3.5.1
    environment:
      ARANGO_NO_AUTH: 1

  spline:
    image: absaoss/spline-rest-server
    ports:
      - 9090:8080
    command: >
      bash -c "echo 'Initializing Spline DB...'
      && curl -O -s https://repo1.maven.org/maven2/za/co/absa/spline/admin/0.5.0/admin-0.5.0.jar
      && java -jar ./admin-0.5.0.jar db-init arangodb://arangodb/spline -s
      && catalina.sh run"
    environment:
      spline.database.connectionUrl: 'arangodb://arangodb/spline'
    links:
      - arangodb

  ui:
    image:  absaoss/spline-web-client
    environment:
      # The consumer URL is used by the web browser
      spline.consumer.url: 'http://localhost:9090/consumer'
    ports:
      - 8080:8080
    links:
      - spline
