---
version: '3'
services:
  arangodb:
    image: arangodb:3.5.1
    environment:
      ARANGO_NO_AUTH: 1
    ports:
      - 8529:8529

  spline:
    image: absaoss/spline-rest-server
    ports:
      - 8080:8080
    environment:
      spline.database.connectionUrl: 'arangodb://arangodb/spline'
    links:
      - arangodb

  ui:
    image:  absaoss/spline-web-client
    environment:
      # The consumer URL is used by the web browser
      spline.consumer.url: 'http://localhost:8080/consumer'
    ports:
      - 9080:8080
    links:
      - spline
