---
version: '3'
services:
  arangodb:
    image: arangodb:${SPLINE_ARANGO_DB_VERSION}
    restart: always
    ports:
      - 8529:8529
    environment:
      ARANGO_NO_AUTH: 1

  spline:
    image: absaoss/spline-rest-server:${SPLINE_VERSION}
    restart: always
    ports:
      - 9090:8080
    command: >
      bash -c "
        until curl --output /dev/null --silent --get --fail http://172.17.0.1:8529/_admin/server/availability
        do
          echo waiting for arango db
          sleep 5
        done
        echo downloading admin-cli &&
        curl -O -s https://repo1.maven.org/maven2/za/co/absa/spline/admin/${SPLINE_VERSION}/admin-${SPLINE_VERSION}.jar &&
        echo creating Spline database &&
        java -jar ./admin-${SPLINE_VERSION}.jar db-init arangodb://arangodb/spline -s &&
        echo starting Spline server &&
        catalina.sh run
      "
    environment:
      spline.database.connectionUrl: 'arangodb://arangodb/spline'
      # by default /dev/random is used which may block
      CATALINA_OPTS: "-Dsecurerandom.source=file:/dev/./urandom -Djava.security.egd=file:/dev/./urandom"
    links:
      - arangodb

  ui:
    image: absaoss/spline-web-client:${SPLINE_VERSION}
    restart: always
    environment:
      # The consumer URL is used by the web browser
      spline.consumer.url: 'http://localhost:9090/consumer'
      # by default /dev/random is used which may block
      CATALINA_OPTS: "-Dsecurerandom.source=file:/dev/./urandom -Djava.security.egd=file:/dev/./urandom"
    ports:
      - 8080:8080
    links:
      - spline
